### ISSUE TITLE
Integrate CHARISMAlab/chairbot_raspberry_pi repo in this 

### ISSUE THREAD

**Issue by CHARISMAlab** [CHARISMAlab/chairbot#5]
Combine both the repos.

**Comment by abhiagni11** [comment]
I have made a new repo 'chairbot_neato-node' which is currently initialised in chairbot01. This package is robot agnostic and will only contain the files that are common to all the robots. Since, we have most of the code present in all the robots, I recommend having this as a separate repo from the central server package.

Note: This package when compiled will automatically use the robots hostname to make unique rosnodes and rostopics
